version: "3.4"
services:
  proxy:
    build: ./docker/nginx
    container_name: nginx-proxy
    volumes:
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  php:
    build: ./docker/php
    container_name: php-fpm
    volumes:
      - ./app:/var/www/html
    expose:
      - "9000"
